grpc:
  client:
    person-service:
      address: static://localhost:9090
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
  server:
    port: 9091
