server:
  port: 8081
spring:
  application:
    name: backend
  profiles:
    active: dev
  cloud:
    config:
      uri: http://47.109.151.152:8888
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
  config:
    import: "configserver:"
