server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ConstantineQAQ/WYNbysj-config.git
          clone-on-start: true
          strict-host-key-checking: false